- hosts: L2
  gather_facts: false
  tasks:
  - name: Enable trunk mode on E0/0 interface
    cisco.ios.ios_config:
      lines:
        - interface Ethernet 0/0
        - switchport trunk encapsulation dot1q
        - switchport mode trunk
        - switchport trunk allowed vlan 1,30,40
  - name: Config vlans on interfaces L2 switches
    cisco.ios.ios_config:
      lines: 
        - interface Ethernet 0/1
        - switchport mode access
        - switchport access vlan 40
        - interface Ethernet 0/2
        - switchport mode access
        - switchport access vlan 30
