apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  volumes:
    - name: logical-master
      emptyDir:
        sizeLimit: 1Gi
    - name: logical-slave
      emptyDir:
        sizeLimit: 1Gi
  containers:
    - name: master
      image: docker.io/library/postgres:17-bookworm 
      volumeMounts:
        - name: logical-master
          mountPath: /docker-entrypoint-initdb.d
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logical-replication
              key: password
    - name: slave
      image: docker.io/library/postgres:17-bookworm
      volumeMounts:
        - name: logical-slave
          mountPath: /docker-entrypoint-initdb.d
      env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: logical-replication
              key: password
